# Check for broken links with lychee
name: Link Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link-check:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@f796c8b7d468feb9b8c0a46da3fac0af6874d374 # v2.2.0
        with:
          args: "--verbose -- ."
          fail: true
          jobSummary: true
