# Check for broken links with lychee
name: Link Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link-check:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@1d97d84f0bc547f7b25f4c2170d87d810dc2fb2c # v2.4.0
        with:
          args: "--verbose -- ."
          fail: true
          jobSummary: true
